# Generated by Django 4.2.30 on 2026-09-11 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticsvisitor',
            name='last_visit',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
