# Generated by Django 4.2.29 on 2026-03-31 15:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_type', models.CharField(max_length=50)),
                ('bucket_path', models.CharField(max_length=500)),
                ('original_name', models.CharField(max_length=255)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'uploaded_files',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
