# Generated by Django 4.2.29 on 2026-03-31 15:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending_approval', 'Pending Approval'), ('lead', 'Lead'), ('approved', 'Approved'), ('intake_submitted', 'Intake Submitted'), ('roles_published', 'Roles Published'), ('roles_confirmed', 'Roles Confirmed'), ('payment_completed', 'Payment Completed'), ('credentials_submitted', 'Credentials Submitted'), ('active_marketing', 'Active Marketing'), ('paused', 'Paused'), ('on_hold', 'On Hold'), ('past_due', 'Past Due'), ('cancelled', 'Cancelled'), ('placed_closed', 'Placed Closed')], default='pending_approval', max_length=30)),
                ('visa_status', models.CharField(blank=True, max_length=50, null=True)),
                ('university', models.CharField(blank=True, max_length=255, null=True)),
                ('degree', models.CharField(blank=True, max_length=255, null=True)),
                ('major', models.CharField(blank=True, max_length=255, null=True)),
                ('graduation_year', models.CharField(blank=True, max_length=10, null=True)),
                ('graduation_date', models.DateField(blank=True, null=True)),
                ('resume_url', models.URLField(blank=True, null=True)),
                ('drive_folder_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('portfolio_url', models.URLField(blank=True, null=True)),
                ('referral_source', models.CharField(blank=True, max_length=255, null=True)),
                ('referral_friend_name', models.CharField(blank=True, max_length=255, null=True)),
                ('current_location', models.CharField(blank=True, max_length=255, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('opt_end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('cal_training_url', models.URLField(blank=True, null=True)),
                ('cal_mock_practice_url', models.URLField(blank=True, null=True)),
                ('cal_interview_training_url', models.URLField(blank=True, null=True)),
                ('cal_interview_support_url', models.URLField(blank=True, null=True)),
                ('cal_operations_call_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'candidates',
            },
        ),
        migrations.CreateModel(
            name='ClientIntake',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.JSONField(default=dict)),
                ('is_locked', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reopened_at', models.DateTimeField(blank=True, null=True)),
                ('reopen_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'client_intake',
            },
        ),
        migrations.CreateModel(
            name='CredentialVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.JSONField(default=dict)),
                ('source_role', models.CharField(default='candidate', max_length=20)),
                ('version', models.IntegerField(default=1)),
                ('changed_fields', models.JSONField(default=list)),
                ('diff_summary', models.JSONField(default=dict)),
                ('full_snapshot', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'credential_versions',
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='InterviewLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interview_type', models.CharField(choices=[('screening_call', 'Screening Call'), ('technical_interview', 'Technical Interview'), ('hr_interview', 'HR Interview'), ('client_round', 'Client Round'), ('final_round', 'Final Round'), ('mock_interview', 'Mock Interview'), ('support_call', 'Support Call')], max_length=50)),
                ('stage_round', models.CharField(blank=True, max_length=100, null=True)),
                ('company_name', models.CharField(max_length=255)),
                ('role_title', models.CharField(max_length=255)),
                ('interview_date', models.DateField()),
                ('interview_time', models.TimeField(blank=True, null=True)),
                ('time_zone', models.CharField(default='America/New_York', max_length=50)),
                ('interviewer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('interview_mode', models.CharField(choices=[('video', 'Video'), ('phone', 'Phone'), ('in_person', 'In Person')], default='video', max_length=20)),
                ('meeting_link', models.URLField(blank=True, null=True)),
                ('outcome', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('selected', 'Selected / Passed'), ('rejected', 'Rejected'), ('follow_up_needed', 'Follow-up Needed'), ('rescheduled', 'Rescheduled'), ('no_show', 'No Show')], default='scheduled', max_length=30)),
                ('difficult_questions', models.TextField(blank=True, null=True)),
                ('feedback_notes', models.TextField(blank=True, null=True)),
                ('support_needed', models.TextField(blank=True, null=True)),
                ('next_round_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'interview_logs',
                'ordering': ['-interview_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('charge_name', models.CharField(max_length=255)),
                ('charge_type', models.CharField(choices=[('monthly_service_fee', 'Monthly Service Fee'), ('mock_practice_fee', 'Mock Practice Fee'), ('interview_support_fee', 'Interview Support Fee'), ('operations_support_fee', 'Operations Support Fee')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('due_date', models.DateField()),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('waived', 'Waived'), ('partially_paid', 'Partially Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_notes', models.TextField(blank=True, null=True)),
                ('is_internal_note', models.BooleanField(default=False)),
                ('previous_due_date', models.DateField(blank=True, null=True)),
                ('due_date_change_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'payments',
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='PlacementClosure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('role_title', models.CharField(max_length=255)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('start_date', models.DateField()),
                ('hr_email', models.EmailField(max_length=254)),
                ('interviewer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('bgv_company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('offer_letter_url', models.URLField(blank=True, null=True)),
                ('placement_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'placement_closures',
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('friend_name', models.CharField(max_length=255)),
                ('friend_email', models.EmailField(max_length=254)),
                ('friend_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('referred_for', models.CharField(blank=True, max_length=255, null=True)),
                ('referral_note', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('contacted', 'Contacted'), ('onboarded', 'Onboarded'), ('closed', 'Closed'), ('rejected', 'Rejected')], default='sent', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'referrals',
            },
        ),
        migrations.CreateModel(
            name='RoleConfirmation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('response', models.CharField(choices=[('accepted', 'Accepted'), ('declined', 'Declined'), ('change_requested', 'Change Requested')], max_length=20)),
                ('change_request_note', models.TextField(blank=True, null=True)),
                ('custom_role_title', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_reason', models.TextField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'role_confirmations',
            },
        ),
        migrations.CreateModel(
            name='RoleSuggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('admin_note', models.TextField(blank=True, null=True)),
                ('candidate_confirmed', models.BooleanField(null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('change_request_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'role_suggestions',
            },
        ),
        migrations.CreateModel(
            name='TrainingScheduleClick',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schedule_type', models.CharField(max_length=100)),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_clicks', to='candidates.candidate')),
            ],
            options={
                'db_table': 'training_schedule_clicks',
            },
        ),
    ]
