# Generated by Django 5.2.8 on 2026-03-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'Pending Approval'), ('lead', 'Lead'), ('approved', 'Approved'), ('intake_submitted', 'Intake Submitted'), ('roles_suggested', 'Roles Suggested'), ('roles_confirmed', 'Roles Confirmed'), ('paid', 'Paid'), ('credential_completed', 'Credential Completed'), ('active_marketing', 'Active Marketing'), ('paused', 'Paused'), ('on_hold', 'On Hold'), ('past_due', 'Past Due'), ('cancelled', 'Cancelled'), ('placed', 'Placed')], default='pending_approval', max_length=30),
        ),
    ]
