# Generated by Django 4.2.29 on 2026-03-31 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roleconfirmation',
            name='suggestion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to='candidates.rolesuggestion'),
        ),
    ]
