# Generated by Django 4.2.29 on 2026-04-07 22:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidates', '0003_alter_roleconfirmation_suggestion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payment',
            new_name='CandidateLegacyPayment',
        ),
    ]
