# Generated by Django 4.2.29 on 2026-04-08 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_create_interestedcandidate'),
        ('candidates', '0004_rename_payment_candidatelegacypayment'),
    ]

    operations = [
    ]
