# Generated by Django 4.2.29 on 2026-04-08 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0005_merge_20260408_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='services',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='interestedcandidate',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='leads/resumes/'),
        ),
        migrations.AddField(
            model_name='interestedcandidate',
            name='selected_services',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
