# Generated by Django 4.2.29 on 2026-04-08 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0006_candidate_resume_file_candidate_services_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'Pending Approval'), ('lead', 'Lead'), ('approved', 'Approved'), ('intake_submitted', 'Intake Submitted'), ('roles_published', 'Roles Published'), ('roles_candidate_responded', 'Roles Candidate Responded'), ('roles_confirmed', 'Roles Confirmed'), ('payment_pending', 'Payment Pending'), ('payment_completed', 'Payment Completed'), ('credentials_submitted', 'Credentials Submitted'), ('active_marketing', 'Active Marketing'), ('paused', 'Paused'), ('on_hold', 'On Hold'), ('past_due', 'Past Due'), ('cancelled', 'Cancelled'), ('placed_closed', 'Placed Closed')], default='pending_approval', max_length=30),
        ),
    ]
