# Generated by Django 4.2.29 on 2026-04-08 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0007_alter_candidate_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='interestedcandidate',
            name='degree',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='interestedcandidate',
            name='major',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
