# Generated by Django 4.2.30 on 2026-07-23 13:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0008_interestedcandidate_degree_interestedcandidate_major'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralEnquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='new', max_length=20)),
                ('seq_number', models.PositiveIntegerField(blank=True, editable=False, help_text='Auto-assigned sequential number for HYREQ display ID', null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'general_enquiries',
            },
        ),
        migrations.AddField(
            model_name='candidate',
            name='bachelors_graduation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='desired_years_of_experience',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='first_entry_us',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='marketing_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='marketing_phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='masters_graduation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='opt_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='personal_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='preferred_locations',
            field=models.TextField(blank=True, help_text='Preferred Location(s)', null=True),
        ),
        migrations.AddField(
            model_name='interestedcandidate',
            name='desired_years_of_experience',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='interestedcandidate',
            name='marketing_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='interestedcandidate',
            name='marketing_phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='interestedcandidate',
            name='seq_number',
            field=models.PositiveIntegerField(blank=True, editable=False, help_text='Auto-assigned sequential number for HYRLD display ID', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='candidatelegacypayment',
            name='charge_type',
            field=models.CharField(choices=[('monthly_service_fee', 'Marketing Service Fee'), ('mock_practice_fee', 'Mock Practice Fee'), ('interview_support_fee', 'Interview Support Fee'), ('operations_support_fee', 'Operations Support Fee')], max_length=50),
        ),
        migrations.AlterField(
            model_name='interviewlog',
            name='interview_type',
            field=models.CharField(choices=[('screening_call', 'Screening Call'), ('assessment', 'Assessment'), ('technical_interview', 'Technical Interview'), ('hr_interview', 'HR Interview'), ('client_round', 'Client Round'), ('final_round', 'Final Round'), ('mock_interview', 'Mock Interview'), ('support_call', 'Support Call')], max_length=50),
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('company_address', models.CharField(blank=True, max_length=511, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('job_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('freelance', 'Freelance'), ('c2c', 'C2C')], default='full_time', max_length=20)),
                ('responsibilities', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='candidates.candidate')),
            ],
            options={
                'db_table': 'work_experiences',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('organization', models.CharField(max_length=255)),
                ('issued_date', models.DateField()),
                ('expires_date', models.DateField(blank=True, null=True)),
                ('credential_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications_data', to='candidates.candidate')),
            ],
            options={
                'db_table': 'certifications',
                'ordering': ['-issued_date'],
            },
        ),
    ]
