# Generated by Django 4.2.29 on 2026-03-31 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recruiters', '0001_initial'),
        ('candidates', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamleadassignment',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teamleadassignment',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_lead_assignments', to='candidates.candidate'),
        ),
        migrations.AddField(
            model_name='teamleadassignment',
            name='team_lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_lead_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recruiterbankdetails',
            name='recruiter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recruiterassignment',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recruiterassignment',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='candidates.candidate'),
        ),
        migrations.AddField(
            model_name='recruiterassignment',
            name='recruiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='joblinkentry',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to='candidates.candidate'),
        ),
        migrations.AddField(
            model_name='joblinkentry',
            name='submission_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_entries', to='recruiters.dailysubmissionlog'),
        ),
        migrations.AddField(
            model_name='joblinkentry',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailysubmissionlog',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='candidates.candidate'),
        ),
        migrations.AddField(
            model_name='dailysubmissionlog',
            name='recruiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
