# Generated by Django 4.2.30 on 2026-07-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysubmissionlog',
            name='is_manual',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='bank_passbook_id',
            field=models.UUIDField(blank=True, help_text='File ID for bank passbook first page', null=True),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='degree',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='government_id_card_id',
            field=models.UUIDField(blank=True, help_text='File ID for Government ID/Aadhaar card', null=True),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='highest_degree_certificate_id',
            field=models.UUIDField(blank=True, help_text='File ID for highest degree certificate', null=True),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='pan_card_id',
            field=models.UUIDField(blank=True, help_text='File ID for PAN card', null=True),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='referral_friend_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='referral_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AlterField(
            model_name='joblinkentry',
            name='application_status',
            field=models.CharField(choices=[('applied', 'Applied'), ('screening', 'Screening'), ('screening_scheduled', 'Screening Scheduled'), ('interview', 'Interview'), ('interview_scheduled', 'Interview Scheduled'), ('rejected', 'Rejected'), ('offer', 'Offer'), ('no_response', 'No Response')], default='applied', max_length=50),
        ),
        migrations.AlterField(
            model_name='joblinkentry',
            name='job_url',
            field=models.URLField(max_length=1000),
        ),
    ]
