# Generated by Django 4.2.30 on 2026-07-31 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0003_dailysubmissionlog_is_manual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblinkentry',
            name='job_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='joblinkentry',
            name='resume_used',
            field=models.TextField(blank=True, null=True),
        ),
    ]
