# Generated by Django 4.2.30 on 2026-08-14 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0009_generalenquiry_candidate_bachelors_graduation_date_and_more'),
        ('recruiters', '0004_alter_joblinkentry_job_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblinkentry',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='joblinkentry',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='joblinkentry',
            name='employment_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='joblinkentry',
            name='experience_required',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='joblinkentry',
            name='salary',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='joblinkentry',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='joblinkentry',
            name='visa_eligibility',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='joblinkentry',
            name='work_mode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='joblinkentry',
            name='application_status',
            field=models.CharField(choices=[('applied', 'Applied'), ('screening', 'Screening'), ('screening_scheduled', 'Screening Scheduled'), ('interview', 'Interview'), ('interview_scheduled', 'Interview Scheduled'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('offer', 'Offer'), ('no_response', 'No Response')], default='applied', max_length=50),
        ),
        migrations.AlterField(
            model_name='joblinkentry',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to='candidates.candidate'),
        ),
        migrations.AlterField(
            model_name='joblinkentry',
            name='submission_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_entries', to='recruiters.dailysubmissionlog'),
        ),
    ]
