# Generated by Django 4.2.30 on 2026-08-19 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0005_joblinkentry_city_joblinkentry_country_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dailysubmissionlog',
            index=models.Index(fields=['candidate_id', '-log_date'], name='idx_dsl_candidate_logdate'),
        ),
        migrations.AddIndex(
            model_name='dailysubmissionlog',
            index=models.Index(fields=['recruiter_id', '-log_date'], name='idx_dsl_recruiter_logdate'),
        ),
        migrations.AddIndex(
            model_name='joblinkentry',
            index=models.Index(fields=['candidate_id', '-created_at'], name='idx_jle_candidate_created'),
        ),
        migrations.AddIndex(
            model_name='joblinkentry',
            index=models.Index(fields=['is_public', '-created_at'], name='idx_jle_public_created'),
        ),
        migrations.AddIndex(
            model_name='joblinkentry',
            index=models.Index(fields=['application_status'], name='idx_jle_app_status'),
        ),
        migrations.AddIndex(
            model_name='joblinkentry',
            index=models.Index(fields=['-created_at'], name='idx_jle_created_desc'),
        ),
        migrations.AddIndex(
            model_name='joblinkentry',
            index=models.Index(fields=['submitted_by_id', '-created_at'], name='idx_jle_submitted_created'),
        ),
    ]
