# Generated by Django 4.2.29 on 2026-04-03 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionaddonassignment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Actual price for this assignment', max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('monthly_service', 'Monthly Service Fee ($400)'), ('mock_practice', 'Mock Practice Fee'), ('interview_support', 'Interview Support Fee'), ('operations_support', 'Operations Support Fee'), ('manual', 'Manual / Other')], default='subscription', max_length=50),
        ),
        migrations.AlterField(
            model_name='razorpayorder',
            name='payment_type',
            field=models.CharField(default='monthly_service', max_length=50),
        ),
    ]
