# Generated by Django 4.2.30 on 2026-07-23 13:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0009_generalenquiry_candidate_bachelors_graduation_date_and_more'),
        ('billing', '0004_alter_invoice_subscription'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscriptionaddonassignment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='invoice',
            name='description',
            field=models.CharField(blank=True, help_text='Description of the invoice, especially useful if not tied to a subscription', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='payment',
            name='addon_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='billing.subscriptionaddonassignment'),
        ),
        migrations.AddField(
            model_name='subscriptionaddonassignment',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addon_assignments', to='candidates.candidate'),
        ),
        migrations.AddField(
            model_name='subscriptionaddonassignment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('monthly_service', 'Marketing Service Fee ($400)'), ('mock_practice', 'Mock Practice Fee'), ('interview_support', 'Interview Support Fee'), ('operations_support', 'Operations Support Fee'), ('addon', 'Add-on Fee'), ('manual', 'Manual / Other')], default='subscription', max_length=50),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expiring_soon', 'Expiring Soon'), ('pending_payment', 'Pending Payment'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending_payment', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriptionaddonassignment',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addon_assignments', to='billing.subscription'),
        ),
        migrations.CreateModel(
            name='PurchaseHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('payment_status', models.CharField(default='completed', max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('purchased_by', models.CharField(default='Candidate', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('addon_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_histories', to='billing.subscriptionaddonassignment')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_histories', to='candidates.candidate')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_histories', to='billing.invoice')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_histories', to='billing.payment')),
            ],
            options={
                'db_table': 'purchase_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
