# Generated by Django 4.2.30 on 2026-09-03 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_city_profile_country_profile_degree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('resigned', 'Resigned'), ('terminated', 'Terminated')], default='active', max_length=20),
        ),
    ]
